edwin:
    edwin_controller:
        type: position_controllers/JointTrajectoryController
        action_ns: "follow_joint_trajectory"
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5

controller_list:
  - name: "edwin/edwin_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory 
    default: true
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
